// Conductor coordination plugin for OpenCode.
// conductor-plugin: generated by `conductor integrate opencode`; re-run it to refresh, or
// `conductor integrate opencode --remove` to uninstall.
//
// Before OpenCode edits a file, this asks the Conductor control plane whether anyone else
// holds it. A hard conflict blocks the edit with the holder named; anything else proceeds.
// Nothing but the tool name and the file path leaves the process — never file contents,
// never the conversation. Any failure to reach Conductor fails open: a coordination outage
// must not brick the editor.

const EDIT_TOOLS = new Set(["edit", "write", "patch", "multiedit", "apply_patch", "notebookedit"]);

function editPath(args) {
  if (!args || typeof args !== "object") return "";
  for (const key of ["filePath", "file_path", "path", "notebookPath", "notebook_path"]) {
    const v = args[key];
    if (typeof v === "string" && v) return v;
  }
  return "";
}

async function runConductor($, cwd, args) {
  // Prefer Bun's shell, which OpenCode hands every plugin; fall back to node's child_process.
  if (typeof $ === "function") {
    try {
      let p = $`conductor ${args}`;
      if (p && typeof p.cwd === "function" && cwd) p = p.cwd(cwd);
      if (p && typeof p.nothrow === "function") p = p.nothrow();
      if (p && typeof p.quiet === "function") p = p.quiet();
      const r = await p;
      return {
        code: typeof r.exitCode === "number" ? r.exitCode : 0,
        stderr: r.stderr ? r.stderr.toString() : "",
        stdout: r.stdout ? r.stdout.toString() : "",
      };
    } catch (err) {
      if (err && typeof err.exitCode === "number") {
        return { code: err.exitCode, stderr: String(err.stderr || ""), stdout: String(err.stdout || "") };
      }
      throw err;
    }
  }
  const { spawnSync } = await import("node:child_process");
  const r = spawnSync("conductor", args, { cwd: cwd || undefined, encoding: "utf8", timeout: 15000 });
  return { code: r.status === null ? 1 : r.status, stderr: r.stderr || "", stdout: r.stdout || "" };
}

export const ConductorPlugin = async ({ $, directory, worktree } = {}) => {
  const cwd = worktree || directory || "";
  return {
    "tool.execute.before": async (input, output) => {
      let blocked = null;
      try {
        const tool = String((input && input.tool) || "").toLowerCase();
        if (!EDIT_TOOLS.has(tool) && !/edit|write|patch/.test(tool)) return;
        const file = editPath(output && output.args);
        if (!file) return;
        const r = await runConductor($, cwd, ["hook", "pre-tool", "--tool", tool, "--path", file]);
        if (r.code === 2) {
          blocked = (r.stderr || "another session holds this file").trim();
        }
      } catch (_) {
        return; // fail open
      }
      if (blocked !== null) {
        throw new Error("Conductor blocked this edit: " + blocked);
      }
    },
    event: async ({ event } = {}) => {
      try {
        if (event && event.type === "session.created") {
          await runConductor($, cwd, ["hook", "session-start"]);
        }
      } catch (_) {
        // never let a coordination hiccup surface as an editor error
      }
    },
  };
};

export default ConductorPlugin;
